#FROM node:9
FROM node:18.1.0-alpine3.15 AS react

WORKDIR /frontend

COPY . .
COPY --chown=node:node package.json .

RUN npm install
COPY --chown=node:node . .
USER node

EXPOSE 3000

CMD ["npm", "run", "build"]
