version: '3.8'

services:
  backend:
    build: backend/.
    command: bash -c 'while !</dev/tcp/db/${DB_PORT}; do sleep 1; done; uvicorn backend.main:app --host 0.0.0.0 --reload'
    volumes:
      - .:/backend
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:${DB_PORT}
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres_data:
